#ifndef CONFIGURATION_H_
#define CONFIGURATION_H_

#define CONFIG_PROCOL_VERSION "1.0"
#define CONFIG_CLIENT_ID "ID0"

#define CONFIG_WIFI_SSID "ESP-Network"
#define CONFIG_WIFI_PASS "esp32-12345678"
#define CONFIG_SERVER_ADDRESS "192.168.0.101"

#endif /* CONFIGURATION_H_ */
