#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := networked_dynamic_execution_environment_for_microcontrollers

include $(IDF_PATH)/make/project.mk

